# Generated by Django 3.1.1 on 2020-12-26 13:48

import datetime
from django.db import migrations, models
import django.db.models.deletion
import pages.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True)),
                ('invitation', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('photo', models.ImageField(default='web-defaults/placeholder.png', upload_to=pages.models.event_upload_path)),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('start_time', models.TimeField(blank=True)),
                ('end_time', models.TimeField(blank=True)),
                ('organizer', models.CharField(blank=True, max_length=250)),
                ('tagline', models.CharField(blank=True, max_length=512)),
                ('details', models.TextField(blank=True)),
                ('link1', models.TextField(blank=True)),
                ('link2', models.TextField(blank=True)),
                ('link3', models.TextField(blank=True)),
                ('invitation', models.TextField(blank=True, default='Singapore Polytechnic Open House 2021 – Info Session')),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('photo', models.ImageField(default='web-defaults/placeholder.png', upload_to=pages.models.school_upload_path)),
                ('email', models.CharField(blank=True, max_length=250)),
                ('phone', models.CharField(blank=True, max_length=250)),
                ('extra', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0)),
                ('appointment', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=250)),
                ('gender', models.CharField(choices=[('-', 'None'), ('M', 'Male'), ('F', 'Female')], default='-', max_length=5)),
                ('phone', models.CharField(blank=True, max_length=250)),
                ('dob', models.DateTimeField(default=datetime.datetime.now)),
                ('attendees', models.IntegerField(default=1)),
                ('participant_type', models.IntegerField(choices=[(0, '-'), (1, 'Parent'), (2, 'O Level School Leaver'), (3, 'N Level School Leaver'), (4, 'ITE Graduate/Student'), (5, 'Secondary School Student (Level), School Teacher/Educator'), (100, 'Others')], default=0)),
                ('participant_other', models.TextField(blank=True)),
                ('infosource_type', models.IntegerField(choices=[(0, '-'), (1, 'Social Media'), (2, 'Mailer from SP'), (100, 'Others')], default=0)),
                ('infosource_other', models.TextField(blank=True)),
                ('question', models.TextField(blank=True)),
                ('interested_in', models.CharField(blank=True, max_length=250)),
                ('is_paid', models.BooleanField(default=False)),
                ('registration_date', models.DateTimeField(default=datetime.datetime.now)),
                ('reminder_on', models.DateField(default=datetime.datetime.now)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.event')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.school'),
        ),
        migrations.CreateModel(
            name='CourseParticipant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.course')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.participant')),
            ],
        ),
        migrations.CreateModel(
            name='CourseEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invitation', models.TextField(blank=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.course')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.event')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.school'),
        ),
    ]
