# Generated by Django 3.1.1 on 2020-10-11 10:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('event_date', models.DateTimeField(default=datetime.datetime.now)),
                ('organizer', models.CharField(blank=True, max_length=250)),
                ('tagline', models.CharField(max_length=512)),
                ('details', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=250)),
                ('gender', models.CharField(choices=[('-', 'None'), ('M', 'Male'), ('F', 'Female')], default='-', max_length=5)),
                ('phone', models.CharField(default=True, max_length=250)),
                ('dob', models.CharField(default=True, max_length=250)),
                ('others', models.TextField(blank=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('registration_date', models.DateTimeField(default=datetime.datetime.now)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.event')),
            ],
        ),
    ]
