# Generated by Django 3.1.1 on 2020-10-13 04:34

from django.db import migrations, models
import pages.models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='photo',
            field=models.ImageField(default='web-defaults/placeholder.png', upload_to=pages.models.event_upload_path),
        ),
    ]
