# Generated by Django 3.1.1 on 2020-10-27 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_courseparticipant'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='invitation',
            field=models.TextField(blank=True),
        ),
    ]
