# Generated by Django 3.1.1 on 2020-11-08 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_school_extra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='extra',
            field=models.IntegerField(choices=[('0', 'No'), ('1', 'Yes')], default=0),
        ),
    ]
