# Generated by Django 3.1.1 on 2020-11-14 11:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_auto_20201110_1048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursesession',
            name='date',
        ),
        migrations.RemoveField(
            model_name='coursesession',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='coursesession',
            name='invitation',
        ),
        migrations.RemoveField(
            model_name='coursesession',
            name='start_time',
        ),
        migrations.AddField(
            model_name='coursesession',
            name='event',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='pages.event'),
            preserve_default=False,
        ),
    ]
