# Generated by Django 3.1.1 on 2020-11-18 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_auto_20201114_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='link1',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='event',
            name='link2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='event',
            name='link3',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='tagline',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
