# Generated by Django 3.1.1 on 2020-11-19 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_auto_20201118_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='invitation',
            field=models.TextField(blank=True, default='Singapore Polytechnic Open House 2021 – Info Session'),
        ),
    ]
